export interface Platform {
  key: string
  name: string
}

export const sourcePlatforms: Platform[] = [
  // Popular platforms first
  { key: 'woocommerce', name: 'WooCommerce' },
  { key: 'magento', name: 'Magento' },
  { key: 'bigcommerce', name: 'BigCommerce' },
  { key: 'prestashop', name: 'PrestaShop' },
  { key: 'opencart', name: 'OpenCart' },
  { key: 'shopware', name: 'Shopware' },
  { key: 'squarespace', name: 'Squarespace' },
  { key: 'wix', name: 'Wix' },
  { key: 'volusion', name: 'Volusion' },
  { key: '3dcart', name: 'Shift4Shop' },
  { key: 'ecwid', name: 'Ecwid' },
  { key: 'lightspeed', name: 'Lightspeed' },
  // Marketplaces
  { key: 'amazon', name: 'Amazon' },
  { key: 'amazonstore', name: 'Amazon Store' },
  { key: 'ebay', name: 'Ebay' },
  { key: 'etsy', name: 'Etsy' },
  { key: 'facebook', name: 'Facebook' },
  { key: 'google', name: 'Google' },
  // A-Z platforms
  { key: 'aabaco', name: 'Aabaco' },
  { key: 'abantecart', name: 'Abantecart' },
  { key: 'ablecommerce', name: 'AbleCommerce' },
  { key: 'aceshop', name: 'AceShop' },
  { key: 'actinic', name: 'Actinic' },
  { key: 'adobe', name: 'Adobe Business Catalyst' },
  { key: 'americommerce', name: 'AmeriCommerce' },
  { key: 'arastta', name: 'Arastta' },
  { key: 'aspdotnet', name: 'AspDotNetStorefront' },
  { key: 'base', name: 'Base' },
  { key: 'bigcartel', name: 'Big Cartel' },
  { key: 'cart66', name: 'Cart66' },
  { key: 'channeladvisor', name: 'ChannelAdvisor' },
  { key: 'commercehq', name: 'CommerceHQ' },
  { key: 'corecommerce', name: 'CoreCommerce' },
  { key: 'cre', name: 'CRE Loaded' },
  { key: 'cscart', name: 'CS-Cart' },
  { key: 'cubecart', name: 'CubeCart' },
  { key: 'drupal', name: 'Drupal Commerce' },
  { key: 'easy', name: 'Easy Digital Downloads' },
  { key: 'ekm', name: 'Ekm' },
  { key: 'epages', name: 'ePages' },
  { key: 'eshop', name: 'Eshop' },
  { key: 'gambio', name: 'Gambio' },
  { key: 'godaddy', name: 'GoDaddy' },
  { key: 'helcimcommerce', name: 'HelcimCommerce' },
  { key: 'hhgmulti', name: 'HHG multistore' },
  { key: 'hikashop', name: 'HikaShop' },
  { key: 'interspire', name: 'Interspire' },
  { key: 'j2store', name: 'J2 Store' },
  { key: 'jigoshop', name: 'Jigoshop' },
  { key: 'jimdo', name: 'Jimdo' },
  { key: 'joocart', name: 'JooCart' },
  { key: 'joomshopping', name: 'JoomShopping' },
  { key: 'joomla', name: 'Joomla' },
  { key: 'jshop', name: 'Jshop Server' },
  { key: 'litecart', name: 'LiteCart' },
  { key: 'loaded', name: 'Loaded Commerce' },
  { key: 'loaded7', name: 'Loaded 7' },
  { key: 'market', name: 'MarketPress' },
  { key: 'memberpress', name: 'MemberPress' },
  { key: 'merchium', name: 'Merchium' },
  { key: 'mijo', name: 'MijoShop' },
  { key: 'mivamerchant', name: 'Miva Merchant' },
  { key: 'mystore', name: 'Mystore.no' },
  { key: 'neto', name: 'Neto' },
  { key: 'nopcommerce', name: 'nopCommerce' },
  { key: 'oscmax', name: 'oscMax' },
  { key: 'oscommerce', name: 'OsCommerce' },
  { key: 'oxideshop', name: 'OXID-eShop' },
  { key: 'palundu', name: 'Palundu' },
  { key: 'pinnaclecart', name: 'PinnacleCart' },
  { key: 'premmerce', name: 'Premmerce' },
  { key: 'redshop', name: 'redSHOP' },
  { key: 'salesforce', name: 'Salesforce' },
  { key: 'sellacious', name: 'Sellacious' },
  { key: 'shopify', name: 'Shopify' },
  { key: 'shopp', name: 'Shopp' },
  { key: 'shopscript', name: 'Shop-Script' },
  { key: 'shopsite', name: 'ShopSite' },
  { key: 'shoptab', name: 'ShopTab' },
  { key: 'smartweb', name: 'SmartWeb' },
  { key: 'sparkpay', name: 'Spark Pay' },
  { key: 'square', name: 'Square' },
  { key: 'squirre', name: 'Squirrelcart' },
  { key: 'storeden', name: 'Storeden' },
  { key: 'storenvy', name: 'Storenvy' },
  { key: 'summercart', name: 'Summer Cart' },
  { key: 'sunshop', name: 'SunShop' },
  { key: 'thirtybees', name: 'Thirty Bees' },
  { key: 'tomatocart', name: 'TomatoCart' },
  { key: 'ubercart', name: 'Ubercart' },
  { key: 'vend', name: 'Vend' },
  { key: 'veyton', name: 'Veyton' },
  { key: 'virtuemart', name: 'VirtueMart' },
  { key: 'visualsoft', name: 'VisualSoft' },
  { key: 'weebly', name: 'Weebly' },
  { key: 'wordpress', name: 'WordPress' },
  { key: 'wpecommerce', name: 'Wp-Ecommerce' },
  { key: 'wpestore', name: 'WP eStore' },
  { key: 'wponline', name: 'WP Online Store' },
  { key: 'xcart', name: 'X-Cart' },
  { key: 'xtcommerce', name: 'Xt:Commerce' },
  { key: 'yahoostore', name: 'Yahoo Store/Aabaco' },
  { key: 'yokart', name: 'Yokart' },
  { key: 'zencart', name: 'ZenCart' },
  { key: 'zoey', name: 'Zoey' },
  // Data imports
  { key: 'csv', name: 'CSV Files' },
  { key: 'dbdump', name: 'Database Dump' },
  { key: 'custom', name: 'Custom Cart' },
]

export const targetPlatforms: Platform[] = [
  { key: 'shopify', name: 'Shopify' },
  { key: 'shopifyplus', name: 'Shopify Plus' },
]
